import { DevicePreset } from './types';

export const DEVICE_PRESETS: DevicePreset[] = [
  // Mobile - Android
  {
    id: 'small-android',
    name: 'Small Android',
    category: 'mobile',
    width: 360,
    height: 640,
    dpr: 2,
    os: 'android',
    aspectRatio: '9:16',
    popular: true,
  },
  {
    id: 'std-android',
    name: 'Standard Android',
    category: 'mobile',
    width: 412,
    height: 915,
    dpr: 2.6,
    os: 'android',
    aspectRatio: '9:20',
    popular: true,
  },
  {
    id: 'large-android',
    name: 'Large Android',
    category: 'mobile',
    width: 412,
    height: 892,
    dpr: 3,
    os: 'android',
    aspectRatio: '9:19.5',
  },

  // Mobile - iPhone
  {
    id: 'small-iphone',
    name: 'Small iPhone (SE)',
    category: 'mobile',
    width: 375,
    height: 667,
    dpr: 2,
    os: 'ios',
    aspectRatio: '9:16',
    popular: true,
  },
  {
    id: 'std-iphone',
    name: 'Standard iPhone (14/15/16)',
    category: 'mobile',
    width: 390,
    height: 844,
    dpr: 3,
    os: 'ios',
    aspectRatio: '9:19.5',
    popular: true,
  },
  {
    id: 'large-iphone',
    name: 'Large iPhone (Plus/Pro Max)',
    category: 'mobile',
    width: 430,
    height: 932,
    dpr: 3,
    os: 'ios',
    aspectRatio: '9:19.5',
    popular: true,
  },

  // Tablets
  {
    id: 'small-tablet',
    name: 'Small Tablet',
    category: 'tablet',
    width: 600,
    height: 960,
    dpr: 1.5,
    os: 'android',
    aspectRatio: '5:8',
  },
  {
    id: 'ipad',
    name: 'iPad / Standard Tablet',
    category: 'tablet',
    width: 768,
    height: 1024,
    dpr: 2,
    os: 'ios',
    aspectRatio: '3:4',
    popular: true,
  },
  {
    id: 'large-ipad',
    name: 'Large iPad Pro',
    category: 'tablet',
    width: 1024,
    height: 1366,
    dpr: 2,
    os: 'ios',
    aspectRatio: '3:4',
    popular: true,
  },
  {
    id: 'android-tablet',
    name: 'Android Tablet (Galaxy Tab)',
    category: 'tablet',
    width: 800,
    height: 1280,
    dpr: 2,
    os: 'android',
    aspectRatio: '10:16',
  },

  // Laptops
  {
    id: 'small-laptop',
    name: 'Small Laptop / Netbook',
    category: 'laptop',
    width: 1280,
    height: 800,
    dpr: 1,
    os: 'generic',
    aspectRatio: '16:10',
  },
  {
    id: 'std-laptop',
    name: 'Standard Laptop (13-14")',
    category: 'laptop',
    width: 1366,
    height: 768,
    dpr: 1,
    os: 'windows',
    aspectRatio: '16:9',
    popular: true,
  },
  {
    id: 'large-laptop',
    name: 'Large Laptop (15-16")',
    category: 'laptop',
    width: 1536,
    height: 864,
    dpr: 1.25,
    os: 'windows',
    aspectRatio: '16:9',
  },

  // Desktops
  {
    id: 'hd-desktop',
    name: 'HD Desktop',
    category: 'desktop',
    width: 1440,
    height: 900,
    dpr: 1,
    os: 'macos',
    aspectRatio: '16:10',
    popular: true,
  },
  {
    id: 'fhd-desktop',
    name: 'Full HD Monitor (1080p)',
    category: 'desktop',
    width: 1920,
    height: 1080,
    dpr: 1,
    os: 'generic',
    aspectRatio: '16:9',
    popular: true,
  },
  {
    id: 'qhd-desktop',
    name: 'QHD / 2K Monitor (1440p)',
    category: 'desktop',
    width: 2560,
    height: 1440,
    dpr: 1,
    os: 'generic',
    aspectRatio: '16:9',
  },
  {
    id: '4k-desktop',
    name: '4K Ultra HD Monitor',
    category: 'desktop',
    width: 3840,
    height: 2160,
    dpr: 2,
    os: 'generic',
    aspectRatio: '16:9',
  },
];

export const COMMON_VIEWPORT_SIZES = [
  { width: 320, height: 568, label: '320 × 568 (Small Mobile)' },
  { width: 360, height: 640, label: '360 × 640 (Android)' },
  { width: 375, height: 667, label: '375 × 667 (iPhone SE)' },
  { width: 390, height: 844, label: '390 × 844 (iPhone 14/15)' },
  { width: 393, height: 852, label: '393 × 852 (Pixel 7/8)' },
  { width: 414, height: 896, label: '414 × 896 (iPhone XR)' },
  { width: 430, height: 932, label: '430 × 932 (iPhone Pro Max)' },
  { width: 768, height: 1024, label: '768 × 1024 (iPad Mini/Air)' },
  { width: 820, height: 1180, label: '820 × 1180 (iPad 10th)' },
  { width: 1024, height: 1366, label: '1024 × 1366 (iPad Pro 12.9)' },
  { width: 1280, height: 720, label: '1280 × 720 (720p HD)' },
  { width: 1366, height: 768, label: '1366 × 768 (Most Common Laptop)' },
  { width: 1440, height: 900, label: '1440 × 900 (MacBook Air)' },
  { width: 1536, height: 864, label: '1536 × 864 (Windows Laptop)' },
  { width: 1920, height: 1080, label: '1920 × 1080 (Full HD 1080p)' },
  { width: 2560, height: 1440, label: '2560 × 1440 (QHD 2K)' },
  { width: 3840, height: 2160, label: '3840 × 2160 (4K UHD)' },
];

export const BREAKPOINTS = [
  320, 360, 375, 390, 414, 480, 576, 640, 768, 820, 992, 1024, 1200, 1280,
  1366, 1440, 1536, 1920, 2560,
];

export const DEFAULT_RESPONSIVE_ISSUES = [
  { id: 'h-scroll', label: 'Horizontal scrolling detected on page', category: 'layout', checked: false },
  { id: 'text-small', label: 'Text is too small or unreadable on mobile', category: 'typography', checked: false },
  { id: 'btn-overflow', label: 'Buttons or CTAs extend outside viewport', category: 'layout', checked: false },
  { id: 'nav-broken', label: 'Navigation menu or hamburger fails to collapse', category: 'navigation', checked: false },
  { id: 'img-overflow', label: 'Images or videos overflow viewport boundary', category: 'media', checked: false },
  { id: 'cards-overflow', label: 'Cards, grids, or columns overlap or clip', category: 'layout', checked: false },
  { id: 'header-broken', label: 'Header or sticky nav obstructs content', category: 'layout', checked: false },
  { id: 'footer-broken', label: 'Footer columns wrap awkwardly or overlap', category: 'layout', checked: false },
  { id: 'modal-overflow', label: 'Modals, popups, or drawers clip offscreen', category: 'layout', checked: false },
  { id: 'forms-overflow', label: 'Form inputs or select dropdowns overflow', category: 'forms', checked: false },
];

export const DEFAULT_ACCESSIBILITY_CHECKS = [
  { id: 'readable-text', label: 'Text Contrast & Legibility', description: 'Body font size >= 16px on mobile, contrast >= 4.5:1', checked: false },
  { id: 'touch-targets', label: 'Touch Target Sizing', description: 'Interactive elements have at least 44x44px clickable area', checked: false },
  { id: 'focus-states', label: 'Focus & Keyboard States', description: 'Focus rings visible when navigating via keyboard Tab', checked: false },
  { id: 'img-alt', label: 'Image Text Alternatives', description: 'Informative images contain descriptive alt text', checked: false },
  { id: 'form-labels', label: 'Form Input Labels', description: 'All form inputs have associated visible labels or aria-labels', checked: false },
];
