'use client';

import React, { useState } from 'react';
import {
  Code2,
  Copy,
  Check,
  Download,
  FileCode,
} from 'lucide-react';
import {
  BorderRadiusConfig,
  ExportTab,
} from '@/lib/borderRadius/borderRadiusTypes';
import {
  generateBorderRadiusCss,
  generateCssClass,
  generateCssVariable,
  generateTailwindClass,
  generateScss,
} from '@/lib/borderRadius/borderRadiusEngine';

interface RadiusCodeExportViewProps {
  config: BorderRadiusConfig;
}

export function RadiusCodeExportView({ config }: RadiusCodeExportViewProps) {
  const [activeTab, setActiveTab] = useState<ExportTab>('css');
  const [classNameInput, setClassNameInput] = useState('rounded-custom');
  const [varNameInput, setVarNameInput] = useState('--custom-radius');
  const [isCopied, setIsCopied] = useState(false);
  const [isCopiedVal, setIsCopiedVal] = useState(false);

  const rawRadius = generateBorderRadiusCss(config);
  const rawCss = `border-radius: ${rawRadius};`;
  const classCode = generateCssClass(config, classNameInput);
  const varCode = generateCssVariable(config, varNameInput);
  const tailwindCode = generateTailwindClass(config);
  const scssCode = generateScss(config, '$custom-radius');

  const getActiveCode = () => {
    switch (activeTab) {
      case 'css':
        return rawCss;
      case 'class':
        return classCode;
      case 'var':
        return varCode;
      case 'tailwind':
        return tailwindCode;
      case 'scss':
        return scssCode;
      default:
        return rawCss;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 1800);
  };

  const handleCopyRawValue = () => {
    navigator.clipboard.writeText(rawRadius);
    setIsCopiedVal(true);
    setTimeout(() => setIsCopiedVal(false), 1800);
  };

  const handleDownloadCss = () => {
    const content = `/* Generated by ToolNest Border Radius Generator */\n${getActiveCode()}\n`;
    const blob = new Blob([content], { type: 'text/css;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `border-radius-${(config.name || 'custom').toLowerCase().replace(/\s+/g, '-')}.css`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full bg-white dark:bg-[#12151c] rounded-2xl border border-zinc-200/80 dark:border-zinc-800 p-4 sm:p-6 shadow-xs transition-colors space-y-4">
      {/* Header & Tabs */}
      <div className="flex items-center justify-between flex-wrap gap-2 pb-3 border-b border-zinc-100 dark:border-zinc-800/80">
        <div className="flex items-center gap-2">
          <Code2 className="w-4 h-4 text-[#5722AF] dark:text-[#9B6BE8]" />
          <h3 className="text-sm font-bold text-zinc-900 dark:text-white">
            Ready-to-Use Code Generator
          </h3>
        </div>

        {/* Tab selection */}
        <div className="flex items-center gap-1 p-0.5 rounded-xl border border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-800/60">
          {(['css', 'class', 'var', 'tailwind', 'scss'] as ExportTab[]).map((tab) => (
            <button
              key={tab}
              type="button"
              onClick={() => setActiveTab(tab)}
              className={`px-2.5 py-1 rounded-lg text-xs font-semibold uppercase tracking-wider transition-all ${
                activeTab === tab
                  ? 'bg-[#5722AF] text-white shadow-xs'
                  : 'text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white'
              }`}
            >
              {tab === 'var' ? 'Variable' : tab}
            </button>
          ))}
        </div>
      </div>

      {/* Sub-inputs when Class or Variable is active */}
      {activeTab === 'class' && (
        <div className="flex items-center gap-2 text-xs">
          <span className="font-semibold text-zinc-500">CSS Class Name:</span>
          <input
            type="text"
            value={classNameInput}
            onChange={(e) => setClassNameInput(e.target.value)}
            className="px-2.5 py-1 rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-[#12121A] text-xs font-mono text-zinc-900 dark:text-white focus:outline-hidden focus:border-[#5722AF]"
          />
        </div>
      )}

      {activeTab === 'var' && (
        <div className="flex items-center gap-2 text-xs">
          <span className="font-semibold text-zinc-500">CSS Variable Name:</span>
          <input
            type="text"
            value={varNameInput}
            onChange={(e) => setVarNameInput(e.target.value)}
            className="px-2.5 py-1 rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-[#12121A] text-xs font-mono text-zinc-900 dark:text-white focus:outline-hidden focus:border-[#5722AF]"
          />
        </div>
      )}

      {/* Code Block Container */}
      <div className="relative rounded-xl bg-gray-950 text-gray-200 font-mono text-xs sm:text-sm p-4 overflow-x-auto border border-gray-800 shadow-inner">
        <pre className="select-all">
          <code>{getActiveCode()}</code>
        </pre>
      </div>

      {/* Action Buttons */}
      <div className="flex items-center justify-between flex-wrap gap-2 pt-1">
        <button
          type="button"
          onClick={handleCopyRawValue}
          className="text-xs text-zinc-500 dark:text-zinc-400 hover:text-[#5722AF] dark:hover:text-[#9B6BE8] font-semibold underline underline-offset-2 flex items-center gap-1 transition-colors"
        >
          {isCopiedVal ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
          <span>{isCopiedVal ? 'Copied value!' : 'Copy raw value only'}</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleDownloadCss}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-zinc-200 dark:border-zinc-700 text-zinc-700 dark:text-zinc-300 text-xs font-semibold hover:bg-zinc-50 dark:hover:bg-zinc-800/60 transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download .css</span>
          </button>
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-4 py-1.5 rounded-xl bg-[#5722AF] hover:bg-[#491B93] text-white text-xs font-semibold shadow-xs transition-all"
          >
            {isCopied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{isCopied ? 'Copied to Clipboard!' : 'Copy Code'}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
