import { SocialMediaPreset, SocialPlatform, PresetCategory } from './socialMediaTypes';

export const SOCIAL_MEDIA_PRESETS: SocialMediaPreset[] = [
  // INSTAGRAM
  {
    id: 'ig-portrait',
    platform: 'instagram',
    category: 'posts',
    name: 'Instagram Post — Portrait',
    width: 1080,
    height: 1350,
    aspectRatio: '4:5',
    description: 'Most engaging feed post format maximizing vertical mobile screen space',
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'ig-square',
    platform: 'instagram',
    category: 'posts',
    name: 'Instagram Post — Square',
    width: 1080,
    height: 1080,
    aspectRatio: '1:1',
    description: 'Classic square feed post matching grid profile thumbnails',
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'ig-landscape',
    platform: 'instagram',
    category: 'posts',
    name: 'Instagram Post — Landscape',
    width: 1080,
    height: 566,
    aspectRatio: '1.91:1',
    description: 'Horizontal post format suitable for panoramic views and wide photography',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'ig-story',
    platform: 'instagram',
    category: 'stories',
    name: 'Instagram Story',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    description: 'Full-screen vertical story format with 250px header/footer safe zones',
    hasSafeArea: true,
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'ig-reel',
    platform: 'instagram',
    category: 'stories',
    name: 'Instagram Reel Cover',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    description: 'Vertical thumbnail cover for Reels with 1:1 feed center crop safe area',
    hasSafeArea: true,
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'ig-profile',
    platform: 'instagram',
    category: 'profile',
    name: 'Instagram Profile Picture',
    width: 320,
    height: 320,
    aspectRatio: '1:1',
    description: 'Circular profile photo displayed across app profiles and comments',
    recommendedFormat: 'png',
  },

  // FACEBOOK
  {
    id: 'fb-post',
    platform: 'facebook',
    category: 'posts',
    name: 'Facebook Shared Post',
    width: 1200,
    height: 630,
    aspectRatio: '1.91:1',
    description: 'Standard horizontal feed post for links and timeline updates',
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'fb-square',
    platform: 'facebook',
    category: 'posts',
    name: 'Facebook Square Post',
    width: 1080,
    height: 1080,
    aspectRatio: '1:1',
    description: 'High-visibility square post format for mobile News Feed',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'fb-story',
    platform: 'facebook',
    category: 'stories',
    name: 'Facebook Story',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    description: 'Full-screen vertical story shown across mobile Facebook & Messenger',
    hasSafeArea: true,
    recommendedFormat: 'jpeg',
  },
  {
    id: 'fb-cover',
    platform: 'facebook',
    category: 'covers',
    name: 'Facebook Page Cover',
    width: 1640,
    height: 856,
    aspectRatio: '1.91:1',
    description: 'Desktop and mobile responsive banner banner for personal profiles and business pages',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'fb-event',
    platform: 'facebook',
    category: 'covers',
    name: 'Facebook Event Cover',
    width: 1920,
    height: 1005,
    aspectRatio: '1.91:1',
    description: 'Top header image for public and private Facebook events',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'fb-profile',
    platform: 'facebook',
    category: 'profile',
    name: 'Facebook Profile Picture',
    width: 400,
    height: 400,
    aspectRatio: '1:1',
    description: 'Circular cropped profile avatar for Facebook accounts',
    recommendedFormat: 'png',
  },

  // YOUTUBE
  {
    id: 'yt-thumbnail',
    platform: 'youtube',
    category: 'thumbnails',
    name: 'YouTube Video Thumbnail',
    width: 1280,
    height: 720,
    aspectRatio: '16:9',
    description: 'High-definition 16:9 preview image shown in search and watch pages',
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'yt-banner',
    platform: 'youtube',
    category: 'covers',
    name: 'YouTube Channel Banner',
    width: 2560,
    height: 1440,
    aspectRatio: '16:9',
    description: 'Channel art with 1546×423 desktop/mobile safe area in center',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'yt-shorts',
    platform: 'youtube',
    category: 'stories',
    name: 'YouTube Shorts / Story',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    description: 'Vertical 9:16 video thumbnail for mobile Shorts shelf',
    hasSafeArea: true,
    recommendedFormat: 'jpeg',
  },
  {
    id: 'yt-profile',
    platform: 'youtube',
    category: 'profile',
    name: 'YouTube Channel Icon',
    width: 800,
    height: 800,
    aspectRatio: '1:1',
    description: 'Avatar for your YouTube channel header, comment replies, and subscriptions',
    recommendedFormat: 'png',
  },

  // LINKEDIN
  {
    id: 'li-post',
    platform: 'linkedin',
    category: 'posts',
    name: 'LinkedIn Post Image',
    width: 1200,
    height: 627,
    aspectRatio: '1.91:1',
    description: 'Standard landscape image post for professional timeline and company updates',
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'li-square',
    platform: 'linkedin',
    category: 'posts',
    name: 'LinkedIn Square Post',
    width: 1200,
    height: 1200,
    aspectRatio: '1:1',
    description: 'Square post format taking higher visual priority in mobile LinkedIn feed',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'li-cover',
    platform: 'linkedin',
    category: 'covers',
    name: 'LinkedIn Personal Background Cover',
    width: 1584,
    height: 396,
    aspectRatio: '4:1',
    description: 'Header banner background displayed behind your profile photo',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'li-profile',
    platform: 'linkedin',
    category: 'profile',
    name: 'LinkedIn Profile Picture',
    width: 400,
    height: 400,
    aspectRatio: '1:1',
    description: 'Professional headshot avatar for LinkedIn connections and search results',
    recommendedFormat: 'png',
  },

  // X (TWITTER)
  {
    id: 'x-post',
    platform: 'x',
    category: 'posts',
    name: 'X (Twitter) Feed Post',
    width: 1600,
    height: 900,
    aspectRatio: '16:9',
    description: 'Landscape post format ensuring clean display without cropping on timeline',
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'x-square',
    platform: 'x',
    category: 'posts',
    name: 'X (Twitter) Square Post',
    width: 1080,
    height: 1080,
    aspectRatio: '1:1',
    description: 'Square media attachment for tweets and carousel ads',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'x-header',
    platform: 'x',
    category: 'covers',
    name: 'X (Twitter) Header Banner',
    width: 1500,
    height: 500,
    aspectRatio: '3:1',
    description: 'Top banner image displayed across desktop and mobile Twitter profiles',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'x-profile',
    platform: 'x',
    category: 'profile',
    name: 'X (Twitter) Profile Picture',
    width: 400,
    height: 400,
    aspectRatio: '1:1',
    description: 'Circular profile photo appearing alongside every tweet and reply',
    recommendedFormat: 'png',
  },

  // PINTEREST
  {
    id: 'pin-standard',
    platform: 'pinterest',
    category: 'posts',
    name: 'Pinterest Standard Pin',
    width: 1000,
    height: 1500,
    aspectRatio: '2:3',
    description: 'Official recommended vertical pin format for maximum feed performance',
    recommendedFormat: 'jpeg',
    isPopular: true,
  },
  {
    id: 'pin-square',
    platform: 'pinterest',
    category: 'posts',
    name: 'Pinterest Square Pin',
    width: 1000,
    height: 1000,
    aspectRatio: '1:1',
    description: 'Square pin format ideal for product catalogs and collections',
    recommendedFormat: 'jpeg',
  },
  {
    id: 'pin-long',
    platform: 'pinterest',
    category: 'posts',
    name: 'Pinterest Long Infographic Pin',
    width: 1000,
    height: 2100,
    aspectRatio: '1:2.1',
    description: 'Extended tall pin ideal for step-by-step guides, infographics, and recipes',
    recommendedFormat: 'jpeg',
  },

  // TIKTOK
  {
    id: 'tiktok-cover',
    platform: 'tiktok',
    category: 'stories',
    name: 'TikTok Video Cover / Photo Post',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    description: 'Full-screen 9:16 vertical image format with bottom & right safe areas for captions',
    hasSafeArea: true,
    recommendedFormat: 'jpeg',
    isPopular: true,
  },

  // SNAPCHAT
  {
    id: 'snap-story',
    platform: 'snapchat',
    category: 'stories',
    name: 'Snapchat Story / Ad',
    width: 1080,
    height: 1920,
    aspectRatio: '9:16',
    description: 'Vertical full-bleed format for personal stories and sponsored geofilters',
    hasSafeArea: true,
    recommendedFormat: 'jpeg',
  },
];

export const POPULAR_PRESET_IDS = [
  'ig-portrait',
  'ig-square',
  'ig-story',
  'fb-post',
  'yt-thumbnail',
  'li-post',
  'x-post',
  'pin-standard',
];

export function getPresetById(id: string): SocialMediaPreset {
  return (
    SOCIAL_MEDIA_PRESETS.find((p) => p.id === id) ||
    SOCIAL_MEDIA_PRESETS[0] // fallback to Instagram portrait
  );
}

export function searchPresets(query: string): SocialMediaPreset[] {
  if (!query || !query.trim()) return SOCIAL_MEDIA_PRESETS;
  const q = query.toLowerCase().trim();
  return SOCIAL_MEDIA_PRESETS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.platform.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      `${p.width}x${p.height}`.includes(q) ||
      p.aspectRatio.includes(q)
  );
}
