'use client';

import React, { useState } from 'react';
import {
  Copy,
  Check,
  Download,
  Code2,
  FileCode,
  FileJson,
  Layers,
} from 'lucide-react';
import { GradientConfig } from '@/lib/gradient/gradientTypes';
import {
  generateGradientCss,
  generateCssRule,
  generateCssVariable,
  generateScss,
  generateJson,
} from '@/lib/gradient/gradientEngine';

interface CSSCodeExportViewProps {
  config: GradientConfig;
}

type CodeTab = 'css' | 'class' | 'var' | 'scss' | 'json';

export function CSSCodeExportView({ config }: CSSCodeExportViewProps) {
  const [activeTab, setActiveTab] = useState<CodeTab>('css');
  const [isCopied, setIsCopied] = useState(false);

  const cssValue = `background: ${generateGradientCss(config)};`;
  const classCode = generateCssRule(config, '.gradient-background');
  const varCode = generateCssVariable(config, '--gradient-primary');
  const scssCode = generateScss(config, '$gradient-primary');
  const jsonCode = generateJson(config);

  const getActiveCode = () => {
    switch (activeTab) {
      case 'css':
        return cssValue;
      case 'class':
        return classCode;
      case 'var':
        return varCode;
      case 'scss':
        return scssCode;
      case 'json':
        return jsonCode;
      default:
        return cssValue;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 1500);
  };

  const handleDownloadCssFile = () => {
    const content = `/* Generated by ToolNest Gradient Generator */\n${classCode}\n`;
    const blob = new Blob([content], { type: 'text/css;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.css`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full bg-white dark:bg-[#12151c] rounded-2xl border border-zinc-200/80 dark:border-zinc-800 p-4 sm:p-6 shadow-xs transition-colors space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-[#5722AF]/10 text-[#5722AF] dark:bg-[#5722AF]/20 dark:text-[#9B6BE8]">
            <Code2 className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-zinc-900 dark:text-white">
              Generated Code
            </h3>
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              Copy production-ready CSS, SCSS, variables, or JSON
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleDownloadCssFile}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
            title="Download .css file"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download .css</span>
          </button>

          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-xl text-xs font-bold bg-[#5722AF] text-white hover:bg-[#481c91] transition-all shadow-xs"
          >
            {isCopied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{isCopied ? 'Copied!' : 'Copy Code'}</span>
          </button>
        </div>
      </div>

      {/* Tab Switcher */}
      <div className="flex items-center gap-1 border-b border-zinc-200 dark:border-zinc-800 overflow-x-auto pb-1 text-xs">
        {[
          { id: 'css' as CodeTab, label: 'CSS Property' },
          { id: 'class' as CodeTab, label: 'CSS Class' },
          { id: 'var' as CodeTab, label: 'CSS Variable' },
          { id: 'scss' as CodeTab, label: 'SCSS' },
          { id: 'json' as CodeTab, label: 'JSON' },
        ].map((tab) => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            className={`px-3 py-1.5 rounded-lg font-semibold whitespace-nowrap transition-all ${
              activeTab === tab.id
                ? 'bg-zinc-200 dark:bg-zinc-800 text-zinc-900 dark:text-white font-bold'
                : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Code Snippet Box */}
      <div className="relative rounded-xl overflow-hidden border border-zinc-800 bg-zinc-900 shadow-inner">
        <pre className="p-4 text-xs font-mono text-zinc-100 overflow-x-auto leading-relaxed">
          <code>{getActiveCode()}</code>
        </pre>
      </div>
    </div>
  );
}
