'use client';

import React, { useState } from 'react';
import {
  Code2,
  Copy,
  Check,
  Download,
  FileCode,
} from 'lucide-react';
import { ShadowLayer, ExportTab } from '@/lib/boxShadow/shadowTypes';
import {
  generateBoxShadowCss,
  generateCssClass,
  generateCssVariable,
  generateTailwindClass,
  generateScss,
} from '@/lib/boxShadow/shadowEngine';

interface ShadowCodeExportViewProps {
  layers: ShadowLayer[];
  shadowName: string;
}

export function ShadowCodeExportView({
  layers,
  shadowName,
}: ShadowCodeExportViewProps) {
  const [activeTab, setActiveTab] = useState<ExportTab>('css');
  const [classNameInput, setClassNameInput] = useState('shadow-custom');
  const [varNameInput, setVarNameInput] = useState('--custom-shadow');
  const [isCopied, setIsCopied] = useState(false);

  const shadowCss = `box-shadow: ${generateBoxShadowCss(layers)};`;
  const classCode = generateCssClass(layers, classNameInput);
  const varCode = generateCssVariable(layers, varNameInput);
  const tailwindCode = generateTailwindClass(layers);
  const scssCode = generateScss(layers, '$custom-shadow');

  const getActiveCode = () => {
    switch (activeTab) {
      case 'css':
        return shadowCss;
      case 'class':
        return classCode;
      case 'var':
        return varCode;
      case 'tailwind':
        return tailwindCode;
      case 'scss':
        return scssCode;
      default:
        return shadowCss;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 1500);
  };

  const handleDownloadCss = () => {
    const content = `/* Generated by ToolNest Box Shadow Generator */\n${classCode}\n`;
    const blob = new Blob([content], { type: 'text/css;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${shadowName.toLowerCase().replace(/[^a-z0-9]/g, '-')}.css`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full bg-white dark:bg-[#12151c] rounded-2xl border border-zinc-200/80 dark:border-zinc-800 p-4 sm:p-6 shadow-xs transition-colors space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-[#5722AF]/10 text-[#5722AF] dark:bg-[#5722AF]/20 dark:text-[#9B6BE8]">
            <Code2 className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-zinc-900 dark:text-white">
              Generated Shadow Code
            </h3>
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              Copy production-ready CSS, Tailwind classes, or SCSS
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleDownloadCss}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download .css</span>
          </button>

          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-xl text-xs font-bold bg-[#5722AF] text-white hover:bg-[#481c91] transition-all shadow-xs"
          >
            {isCopied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{isCopied ? 'Copied!' : 'Copy Code'}</span>
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center justify-between flex-wrap gap-2 border-b border-zinc-200 dark:border-zinc-800 pb-1 text-xs">
        <div className="flex items-center gap-1 overflow-x-auto">
          {[
            { id: 'css' as ExportTab, label: 'CSS Property' },
            { id: 'class' as ExportTab, label: 'CSS Class' },
            { id: 'var' as ExportTab, label: 'CSS Variable' },
            { id: 'tailwind' as ExportTab, label: 'Tailwind CSS' },
            { id: 'scss' as ExportTab, label: 'SCSS' },
          ].map((tab) => (
            <button
              key={tab.id}
              type="button"
              onClick={() => setActiveTab(tab.id)}
              className={`px-3 py-1.5 rounded-lg font-semibold whitespace-nowrap transition-all ${
                activeTab === tab.id
                  ? 'bg-zinc-200 dark:bg-zinc-800 text-zinc-900 dark:text-white font-bold'
                  : 'text-zinc-500 hover:text-zinc-900 dark:hover:text-white'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Custom Class / Variable name inputs */}
        {activeTab === 'class' && (
          <div className="flex items-center gap-1 text-[11px]">
            <span className="text-zinc-500">Class Name:</span>
            <input
              type="text"
              value={classNameInput}
              onChange={(e) => setClassNameInput(e.target.value)}
              className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded px-2 py-0.5 font-mono outline-none w-32"
            />
          </div>
        )}

        {activeTab === 'var' && (
          <div className="flex items-center gap-1 text-[11px]">
            <span className="text-zinc-500">Variable:</span>
            <input
              type="text"
              value={varNameInput}
              onChange={(e) => setVarNameInput(e.target.value)}
              className="bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded px-2 py-0.5 font-mono outline-none w-36"
            />
          </div>
        )}
      </div>

      {/* Code Display Box */}
      <div className="relative rounded-xl overflow-hidden border border-zinc-800 bg-zinc-900 shadow-inner">
        <pre className="p-4 text-xs font-mono text-zinc-100 overflow-x-auto leading-relaxed">
          <code>{getActiveCode()}</code>
        </pre>
      </div>
    </div>
  );
}
